name: Deploy to cPanel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: CI=false npm run build

      - name: Upload files to cPanel
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: 68.183.40.171
          username: root
          password: bVXrcBQ0M8XrQsa
          local-dir: build/
          server-dir: /var/ww/html/app/user/build/