name: Deploy to Digital Ocean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build 
          

      - name: Deploy to Droplet
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            SOURCE: ${{ secrets.SOURCE_DIR }}
            REMOTE_HOST: ${{ secrets.SERVER_IP }}
            REMOTE_USER: ${{ secrets.SERVER_USER_NAME }}
            TARGET: ${{ secrets.TARGET_DIR }}
            

